"""KB template: file contents and contract validation for knowledge bases."""

import os

# --- Template file contents ---

AGENTS_MD = """\
# Conventions

You own this knowledge base. The `kb` CLI gives you safe file operations
and retrieval aids; the organisation, vocabulary, and workflow are yours.

**This file is yours to edit.** It's seeded with defaults that the
consolidation research (Microsoft "AI agent amnesia", Karpathy's
LLM-wiki gist) finds useful, but nothing in the CLI enforces them. If a
default doesn't fit this KB's domain, change it here and proceed. Append
a one-line entry to `LOG.md` when you do.

## Working defaults

### Capture

- By default, stage raw or uncertain material in `inbox/` before treating
  it as canonical. `kb stage --note|--file|--url` writes there.
- Preserve provenance — link or name the source when you add a fact.
- Prefer concise, durable notes over transcripts.
- Never store secrets, credentials, tokens, or sensitive personal data
  (SSN, financial, medical, etc.). Non-sensitive personal facts
  (birthdays, contacts, addresses) are fine in a personal KB.

### Consolidation

- By default, `inbox/` holds source material and a separate canonical
  section (`knowledge/` in the seed) holds synthesised output. Moving
  material between them is a deliberate act — the research calls this
  the "maturation gate" and credits it with most of the quality win.
- Before rewriting canonical pages, read `BRIEF.md`, `INDEX.md`,
  `LOG.md`, and existing pages so you don't duplicate or contradict.
- Prefer updating an existing page over creating a new one.
- Preserve consumed inbox/source paths in the canonical page or
  `LOG.md` so the audit trail survives.
- Use git history as the audit trail. The CLI auto-commits writes.

## Organising the KB

- The CLI auto-discovers top-level directories that contain `.md` files
  and treats them as indexable sections (excluding `inbox/`, `sources/`,
  `tools/`). You can grow `runbooks/`, `decisions/`, `specs/`,
  `recipes/`, etc. without touching the plugin.
- `kb stage --kind <label>` accepts any string. The CLI suggests a few
  starting points (`decision`, `domain-fact`, `codebase-fact`,
  `runbook-note`, `retrospective`, `followup`, `raw-note`); invent your
  own when the domain wants them.
- `INDEX.md` is the narrative, hand-curated entry point — group pages
  by topic, audience, or workflow. `index.json` (rebuilt by
  `kb reindex`) is the machine-readable manifest used by `kb recall`.

## When to update this file

If you find yourself working around a default repeatedly, change it
here. Common cases:

- A new top-level directory the KB needs (and the convention for what
  lives there).
- A domain-specific vocabulary of `--kind` labels.
- A stricter or looser dry-run policy for canonical edits.
- A retention rule for processed inbox material (default: move to
  `inbox/processed/`, never delete in v0).

Edits to this file are versioned in git like anything else. Use that
history when reasoning about how the KB's conventions evolved.
"""

BRIEF_TEMPLATE = """\
# {name} KB Brief

## Purpose

Short description of what this KB contains and when agents should use it.

## Scope

- Included:
- Excluded:

## Key Areas

- `knowledge/` - synthesized durable knowledge
- `inbox/` - staged notes awaiting consolidation
- `sources/` - optional source material or pointers
- `tools/` - reserved for future reusable diagnostics
- `LOG.md` - maintenance and consolidation journal

## Retrieval Guidance

Start with `BRIEF.md`, search before opening broad files, and prefer scoped context.
"""

INDEX_MD = """\
# Index

Hand-curated navigational index. Group canonical knowledge pages
semantically (by topic, audience, or workflow) — this file is the
narrative entry point.

For a programmatic manifest (path, title, tags, summary, word count,
last modified) used by `kb recall`, see `index.json`, which is
regenerated by `kb reindex`.

## Canonical Knowledge

- [Knowledge README](knowledge/README.md)

## Staging

- [Inbox README](inbox/README.md)

## Sources

- [Sources README](sources/README.md)

## Maintenance

- [Maintenance Log](LOG.md)
- [Tools README](tools/README.md)
"""

LOG_MD = """\
# Maintenance Log

Append short entries when inbox notes are consolidated into canonical knowledge.

Each entry should include:

- date
- agent/tool identity when useful
- inbox/source paths consumed
- canonical pages created or updated
- unresolved questions or follow-up work
"""

NOTES_README = """\
# Notes

Short, single-paragraph durable facts that are expensive to re-derive but
too small to deserve a canonical page in `knowledge/`. Project, domain,
codebase, or personal-life facts all qualify if they meet the litmus test.

Examples of what belongs here:

- "EMMA's nightly job runs at 02:00 UTC via cron." (project)
- "The `analyze_meter_drift` function returns null when input has <30 days
  of data." (codebase)
- "We tried PostgreSQL JSON columns in 2024 and abandoned them — search
  latency was 3x." (domain)
- "My birthday is 15 November." (personal — fits if this is a personal KB)

Format: one Markdown file per note at
`notes/<YYYY>/<MM>/<timestamp>-<slug>.md`, with `tags:` and `created_at:`
frontmatter and the fact as the body.

This directory is **append-only**: `kb-dream` never touches it. Notes here
are final, not raw material.

What does NOT belong here:

- User preferences about agent behaviour ("address me as bro", "I prefer
  rebase") — use Claude's auto-memory.
- Short-lived project state (current task, last error) — use Claude's
  auto-memory.
- Normative workflow rules ("don't push to master") — use CLAUDE.md or
  AGENTS.md.
- Long-form synthesised knowledge — write to `knowledge/` via `kb-dream`.
- Material that needs further processing — stage to `inbox/` instead.
"""

INBOX_README = """\
# Inbox

Staging area for raw or uncertain material, awaiting consolidation into
`knowledge/`.

Three shapes of material live here:

- **Notes** — agent-written, semi-structured. Produced by
  `kb stage --note ...`. YAML frontmatter at top (`kind`, `created_at`,
  optional `source`/`title`). The note owns its heading.
- **Documents** — any text file copied verbatim. Produced by
  `kb stage --file <path>` or by dropping a Markdown file directly into
  this directory. No frontmatter, no auto-heading. Provenance lives in
  the git commit message.
- **URL pointers** — produced by `kb stage --url <url>`. Frontmatter has
  `kind: url` and `url: <url>`; the next `kb-dream` pass fetches and
  summarises the link.

Processed material may be moved under `inbox/processed/` after its
durable content is synthesized into canonical knowledge.
"""

KNOWLEDGE_README = """\
# Knowledge

Canonical synthesized knowledge. Treat as durable reference.
"""

SOURCES_README = """\
# Sources

Optional source material, links, or pointers to external references.
"""

TOOLS_README = """\
# Tools

Reserved for future reusable scripts and diagnostics. Not executed in v0.
"""

GITIGNORE = """\
# OS
.DS_Store
Thumbs.db

# Editor
*.swp
*.swo
*~

# Secrets — never commit
.env
*.pem
*.key
"""

# Required contract files/dirs
CONTRACT_FILES = ["AGENTS.md", "BRIEF.md", "INDEX.md", "LOG.md"]
CONTRACT_DIRS = ["inbox", "knowledge", "notes", "sources", "tools"]


def create_kb(path, name):
    """Create a KB from template at the given path. Path must not exist or be
    empty (caller checks)."""
    os.makedirs(path, exist_ok=True)

    def _write(relpath, content):
        full = os.path.join(path, relpath)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w") as f:
            f.write(content)

    _write("AGENTS.md", AGENTS_MD)
    _write("BRIEF.md", BRIEF_TEMPLATE.format(name=name))
    _write("INDEX.md", INDEX_MD)
    _write("LOG.md", LOG_MD)
    _write("inbox/README.md", INBOX_README)
    _write("knowledge/README.md", KNOWLEDGE_README)
    _write("notes/README.md", NOTES_README)
    _write("sources/README.md", SOURCES_README)
    _write("tools/README.md", TOOLS_README)
    _write(".gitignore", GITIGNORE)


def validate_kb_contract(path):
    """Check for missing contract files/dirs. Returns list of missing items."""
    missing = []
    for f in CONTRACT_FILES:
        if not os.path.isfile(os.path.join(path, f)):
            missing.append(f)
    for d in CONTRACT_DIRS:
        if not os.path.isdir(os.path.join(path, d)):
            missing.append(d + "/")
    return missing
